DROP DATABASE IF EXISTS `piwigo`;
CREATE DATABASE `piwigo` /*!40100 DEFAULT CHARACTER SET utf8 */;

DROP DATABASE IF EXISTS `messaging`;
CREATE DATABASE `messaging` /*!40100 DEFAULT CHARACTER SET utf8 */;

DROP DATABASE IF EXISTS `rekognition`;
CREATE DATABASE `rekognition` /*!40100 DEFAULT CHARACTER SET utf8 */;
