DROP DATABASE IF EXISTS `{{pwgo_db}}`;
CREATE DATABASE `{{pwgo_db}}` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;

DROP DATABASE IF EXISTS `{{msg_db}}`;
CREATE DATABASE `{{msg_db}}` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
