"""repository of string resources"""
LOG_ADD_IMG_FACES = lambda fname: f"adding faces from {fname} to face index"
LOG_DETECT_IMG_FACES = lambda fname: f"detecting faces in {fname}"
LOG_MOVE_IMG = lambda fname: f"Moving {fname} from autotag to processed auto tag album"
LOG_QUEUE_EVT = "EventDispatcher: queuing event"
LOG_HANDLE_SIG = lambda sig: f"MetadataAgent: handling signal {sig}"
LOG_WORKER_ERRORS = lambda n: f"{n} workers encountered problems."
LOG_VFS_REBUILD_REMOVE = lambda path: f"removing all filesystem objects from {path}"
LOG_VFS_REBUILD_CREATE = lambda n: f"recreating virtualfs symlinks from {n} database rows"
LOG_INITIALIZE_DB = "Running database initialization"
LOG_PRG_OPT = lambda k,v: f"initializing program config with {k}={v}"
LOG_AGNT_OPT = lambda k,v: f"initializing agent config with {k}={v}"
