version: '3.7'

services:
    app:
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        container_name: dev-env
        network_mode: host
        volumes:
            - ..:/workspace
        user: vscode
        command: sleep infinity

    mariadb:
        image: mariadb
        container_name: dev-db
        network_mode: host
        #ports:
        #    - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: vscode
        command: mysqld --log-bin --binlog-format=ROW --server-id=1
        restart: unless-stopped
