version: '3.7'

volumes:
  mysqld:

services:
    app:
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        container_name: dev-env
        volumes:
            - ..:/workspace
            - mysqld:/var/run/mysqld
        user: vscode
        command: sleep infinity

    mariadb:
        image: mariadb
        container_name: dev-db
        ports:
           - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: vscode
        volumes:
            - mysqld:/var/run/mysqld
        command: mysqld --log-bin --binlog-format=ROW --server-id=1
        restart: unless-stopped
