# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  push:
    tags:
    - '*'

defaults:
  run:
    working-directory: utilities_pkg

jobs:
  deploy:
    name: upload to Amazon CodeArtifact
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true
        token: ${{ secrets.REPO_ACCESS_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Configure twine for CodeArtifact
      run: |
        aws codeartifact login \
        --tool twine --repository com.grinols.pkg \
        --domain grinolscom --domain-owner 645687379263
    
    - name: Build and publish
      run: |
        python setup.py sdist bdist_wheel
        twine upload --repository codeartifact dist/*
