name: CI/CD

on: [push]

defaults:
  run:
    working-directory: .devcontainer

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: build containers
        run: docker-compose up -d
      - name: test utilities_pkg
        run: docker exec dev-env pytest /workspace/utilities_pkg
      - name: stop containers
        run: docker-compose down
