name: CI/CD

on: [push]

jobs:
  test:
    defaults:
      run:
        working-directory: .devcontainer

    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: log working dir
        run: ls -la
      
      - name: install mysql client
        run: sudo apt-get update && sudo apt-get -y install default-mysql-client
      
      - name: build containers
        run: docker-compose up -d

      - name: install project
        run: docker exec dev-env pip3 --disable-pip-version-check --no-cache-dir install /workspace/pwgo_helper_package[dev]
      
      - name: wait for mariadb
        run: while ! mysqladmin ping -h"127.0.0.1" --silent; do sleep 1; done
        timeout-minutes: 1
      
      - name: test pwgo_helper_pkg
        run: docker exec dev-env pytest /workspace/pwgo_helper_package
      
      - name: stop containers
        run: docker-compose down

  deploy:
    defaults:
      run:
        working-directory: pwgo_helper_package
    
    name: Deploy to container registry
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')

    permissions:
      packages: write
      contents: read

    steps:
      - name: Set up Docker Builder
        uses: docker/setup-buildx-action@v1

      - name: login to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: log working dir
        run: echo "::debug working dir->$CWD"

      - name: extract version
        run: echo "::set-output name=PWGO_HLPR_VER::$(cat setup.py | grep version= | sed 's/.*version=[[:punct:]]\([[:digit:]]\+\.[[:digit:]]\+\.[[:digit:]]\+\)[[:punct:]].*/\1/')"
        id: extract-ver

      - name: build and publish image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:latest
          labels: ${{ steps.extract-ver.outputs.PWGO_HLPR_VER }}
