name: CI/CD

on: [push]

defaults:
  run:
    working-directory: .devcontainer

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      
      - name: install mysql client
        run: sudo apt-get install mysql-client
      
      - name: build containers
        run: docker-compose up -d
      
      - name: wait for mariadb
        run: while ! mysqladmin ping -h"127.0.0.1" --silent; do sleep 1; done
        timeout-minutes: 1
      
      - name: test utilities_pkg
        run: docker exec dev-env pytest /workspace/utilities_pkg
      
      - name: stop containers
        run: docker-compose down

  deploy:
    name: Deploy to container registry
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')

    permissions:
      packages: write
      contents: read

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Set up Docker Builder
        uses: docker/setup-buildx-action@v1

      - name: login to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: build and publish image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.REPO_ACCESS_TOKEN }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:latest
