name: Publish Photo Management image

on:
  push:
    tags:
    - '*'

jobs:
  push_to_registry:
    name: Push photo mgmt image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: login to registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and publish image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            docker.pkg.github.com/${{ github.repository }}/octo-image:${{ github.sha }}
            docker.pkg.github.com/${{ github.repository }}/octo-image:${{ github.ref }}
