name: Publish Photo Management image

on:
  push:
    tags:
    - '*'

jobs:
  push_to_registry:
    name: Push photo mgmt image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Set up Docker Builder
        uses: docker/setup-buildx-action@v1

      - name: login to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: build and publish image
        uses: docker/build-push-action@v2
        with:
          context: .
          version: latest
          file: Dockerfile
          push: true
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.REPO_ACCESS_TOKEN }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:latest
